#pragma config(Motor,  port2,           MobileGoalL,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           MobileGoalR,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RightSide1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RightSide2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LeftSide1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LeftSide2,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  motor[RightSide1] = 127;
	motor[RightSide2] = 127;
	motor[LeftSide1] = 127;
	motor[LeftSide2] = 127;
	wait1Msec(3000);
	//The robot drives forward at half speed for 3 seconds.
	motor[RightSide1] = 127;
	motor[RightSide2] = 127;
	motor[LeftSide1] = 0;
	motor[LeftSide2] = 0;
	wait1Msec(1000);
	//The robot spins in a circle at half speed for 10 seconds.
	motor[RightSide1] = 0;
	motor[RightSide2] = 0;
	motor[LeftSide1] = 0;
	motor[LeftSide2] = 0;
	wait1Msec(2000);
	//The robot stops for a total of 2 seconds.
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    	// User control code here, inside the loop
bStopTasksBetweenModes = true;

while(1 == 1) {
		//Left Drive controlled by Left Joystick, Right Drive controlled by Right Stick.
		motor[RightSide1] = vexRT[Ch2];
		motor[RightSide2] = vexRT[Ch2];
		motor[LeftSide1] = vexRT[Ch3];
		motor[LeftSide2] = vexRT[Ch3];




		//Mobile goal controls

	if (vexRT [Btn6U] == 1)	{
			motor[MobileGoalL] = 127;
			motor[MobileGoalR] = 127;
			} else if(vexRT[Btn6D] == 1) {
			motor[MobileGoalL] = -127;
			motor[MobileGoalR] = -127;
			}
			else {
			motor[MobileGoalL] = 0;
			motor[MobileGoalR] = 0;
		}
    UserControlCodePlaceholderForTesting();
  }
 }
}
